"""CLI entry points and the runbook (Phase F 3.8).

The requirement is that a report "can be regenerated by command and agrees with
the append-only record". So the assertions here are about agreement, not about
output shape: a CLI that renders a slightly different conclusion from the stored
record would be worse than no CLI, because an operator would trust the fresh-looking
one.
"""

import json

import pytest

from ats.workflow import shadow_compare as sc
from ats.workflow import shadow_ledger as sl
from ats.workflow import shadow_reports as sr
from ats.runtime import cli


@pytest.fixture
def store(tmp_path):
    return tmp_path / "reports.sqlite"


def _run(capsys, argv):
    code = cli.main(argv)
    out = capsys.readouterr().out
    return code, json.loads(out) if out.strip() else {}


_CLEAN_LEFT = {
    "_packet": {"doc": 1},
    "schedule_omission": ["t1"],
    "analyst_output": ["a"],
    "risk_verdict": {"verdict": "pass"},
    "approval_chain": {"verdict": "approved", "round_no": 1},
    "trade_attribution": {"o1": "chained"},
}
_RISK_DIVERGED_RIGHT = dict(
    _CLEAN_LEFT, risk_verdict={"verdict": "reject"})


# --------------------------------------------------------------------------- #
# the shadow command exists and is separate
# --------------------------------------------------------------------------- #

def test_shadow_is_its_own_command_not_a_workflow_action(capsys):
    """Different artefacts with different rules.

    One command whose actions span both makes the read-only ones look as if they
    can also mutate.
    """
    with pytest.raises(SystemExit):
        cli.main(["shadow", "--help"])


def test_an_unknown_report_id_is_reported_not_silently_empty(capsys, store):
    """"no events" and "no such report" are different answers to one question."""
    code, payload = _run(capsys, ["shadow", "report", "--report-id", "typo",
                                  "--db", str(store)])
    assert code == 1
    assert "typo" in payload["error"]


def test_a_missing_required_flag_is_an_error(capsys, store):
    with pytest.raises(SystemExit):
        cli.main(["shadow", "events", "--db", str(store)])


def test_malformed_json_is_reported_as_such(capsys, store):
    with pytest.raises(SystemExit):
        cli.main(["shadow", "compare", "--report-id", "r", "--left-json", "{oops",
                  "--db", str(store)])


# --------------------------------------------------------------------------- #
# report regeneration agrees with the record
# --------------------------------------------------------------------------- #

def test_compare_records_and_prints_the_same_verdicts(capsys, store):
    code, payload = _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_CLEAN_LEFT),
        "--db", str(store)])
    assert code == 0

    stored = sr.read_state("rep-1", path=store)
    # `surfaces` is a verdict map, so the comparison is against it directly.
    assert payload["verdicts"] == stored.surfaces
    assert {row["surface"] for row in payload["surfaces"]} == set(sc.SIX_SURFACES)


def test_the_report_action_reproduces_the_stored_state(capsys, store):
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_CLEAN_LEFT),
        "--db", str(store)])
    _, payload = _run(capsys, ["shadow", "report", "--report-id", "rep-1",
                               "--db", str(store)])

    assert payload["surfaces"] == sr.read_state("rep-1", path=store).surfaces
    assert payload["scope_hash"] == sr.read_state("rep-1", path=store).scope_hash


def test_events_are_listed_in_order(capsys, store):
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_CLEAN_LEFT),
        "--db", str(store)])
    _run(capsys, ["shadow", "signoff", "--report-id", "rep-1",
                  "--actor", "owner", "--reason", "clean", "--db", str(store)])

    _, payload = _run(capsys, ["shadow", "events", "--report-id", "rep-1",
                               "--db", str(store)])
    assert [e["event_type"] for e in payload] == ["comparison", "signoff"]


# --------------------------------------------------------------------------- #
# check is a gate, not a printout
# --------------------------------------------------------------------------- #

def test_check_exits_non_zero_when_the_report_is_not_citable(capsys, store):
    """So a runbook script cannot pass on a citation it just proved invalid."""
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_RISK_DIVERGED_RIGHT),
        "--db", str(store)])

    code, payload = _run(capsys, ["shadow", "check", "--report-id", "rep-1",
                                  "--scope-json", '{"p": ["x"]}',
                                  "--db", str(store)])
    assert code == 1
    assert payload["citable"] is False
    assert any(sc.RISK_VERDICT in problem for problem in payload["problems"])


def test_check_exits_zero_for_a_signed_off_clean_report(capsys, store):
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_CLEAN_LEFT),
        "--db", str(store)])
    _run(capsys, ["shadow", "signoff", "--report-id", "rep-1",
                  "--actor", "owner", "--reason", "clean",
                  "--required-surface", sc.RISK_VERDICT,
                  "--db", str(store)])

    code, payload = _run(capsys, ["shadow", "check", "--report-id", "rep-1",
                                  "--scope-json", '{"p": ["x"]}',
                                  "--db", str(store)])
    assert code == 0
    assert payload["citable"] is True


# --------------------------------------------------------------------------- #
# disposition and revocation through the CLI
# --------------------------------------------------------------------------- #

def test_a_rejection_through_the_cli_flips_the_status(capsys, store):
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "trader", "--batch-class", "trading",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(_CLEAN_LEFT),
        "--right-json", json.dumps(_CLEAN_LEFT),
        "--db", str(store)])
    _, payload = _run(capsys, ["shadow", "reject", "--report-id", "rep-1",
                               "--actor", "reviewer", "--reason", "not good",
                               "--db", str(store)])
    assert payload["status"] == sr.REJECTED
    # The comparison is still there.
    assert len(sr.events("rep-1", path=store)) == 2


def test_accepting_a_divergence_through_the_cli(capsys, store):
    left = dict(_CLEAN_LEFT, analyst_output=[f"p-{i}" for i in range(20)])
    right = dict(left, analyst_output=[f"other-{i}" for i in range(20)])
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "chief", "--batch-class", "decision",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(left), "--right-json", json.dumps(right),
        "--db", str(store)])

    _, payload = _run(capsys, [
        "shadow", "accept", "--report-id", "rep-1", "--surface", sc.ANALYST_OUTPUT,
        "--actor", "owner", "--authority", "chief_owner",
        "--reason", "role rewrite verified", "--db", str(store)])
    assert payload["surface"] == sc.ANALYST_OUTPUT
    assert sr.read_state("rep-1", path=store).unaccepted == ()


def test_acceptances_can_be_listed(capsys, store):
    left = dict(_CLEAN_LEFT, analyst_output=[f"p-{i}" for i in range(20)])
    right = dict(left, analyst_output=[f"other-{i}" for i in range(20)])
    _run(capsys, [
        "shadow", "compare", "--report-id", "rep-1", "--run-id", "r1",
        "--consumer-id", "chief", "--batch-class", "decision",
        "--scope-json", '{"p": ["x"]}', "--packet-hash", "p1",
        "--expected-triggers-json", '["t1"]',
        "--left-json", json.dumps(left), "--right-json", json.dumps(right),
        "--db", str(store)])
    _run(capsys, [
        "shadow", "accept", "--report-id", "rep-1", "--surface", sc.ANALYST_OUTPUT,
        "--actor", "owner", "--authority", "chief_owner",
        "--reason", "verified", "--db", str(store)])

    _, payload = _run(capsys, ["shadow", "acceptances", "--report-id", "rep-1",
                               "--db", str(store)])
    assert len(payload) == 1
    assert payload[0]["authority"] == "chief_owner"


# --------------------------------------------------------------------------- #
# the shadow ledger through the CLI
# --------------------------------------------------------------------------- #

def test_intents_rebuild_attribution_through_the_cli(capsys, tmp_path):
    order_db = tmp_path / "orders.sqlite"
    sl.record_intent(sl.ShadowIntent(
        intent_id="i1", run_id="run-1", cycle_id="c1", symbol="MU",
        action="buy", quantity=100.0, decision_hash="dh", approval_id="a1"),
        path=order_db)

    _, payload = _run(capsys, ["shadow", "intents", "--cycle-id", "c1",
                               "--order-db", str(order_db)])
    assert payload["order_count"] == 1
    assert payload["every_order_authorized"] is True


def test_attest_through_the_cli(capsys, tmp_path):
    order_db = tmp_path / "orders.sqlite"
    sl.record_intent(sl.ShadowIntent(
        intent_id="i1", run_id="run-1", cycle_id="c1", symbol="MU",
        action="buy", quantity=100.0), path=order_db)

    _, payload = _run(capsys, ["shadow", "attest", "--run-id", "run-1",
                               "--order-db", str(order_db)])
    assert payload["intent_count"] == 1
    assert payload["prohibition_exercised"] is False


# --------------------------------------------------------------------------- #
# the runbook exists and its commands are the real ones
# --------------------------------------------------------------------------- #

def test_the_runbook_documents_every_cli_action():
    """A runbook whose commands do not run is worse than none: it is trusted."""
    from pathlib import Path

    repo = Path(__file__).resolve().parents[1]
    runbook = repo / "docs" / "SHADOW_COMPARISON_RUNBOOK.md"
    assert runbook.exists(), "the runbook is part of the deliverable"

    text = runbook.read_text(encoding="utf-8")
    for action in ("report", "events", "acceptances", "compare", "signoff",
                   "reject", "revoke", "accept", "check", "intents", "attest"):
        assert f"ats shadow {action}" in text, f"{action} is undocumented"


def test_the_runbook_names_the_commands_that_must_not_be_taken():
    """The prohibitions are the part an operator most needs stated."""
    from pathlib import Path

    repo = Path(__file__).resolve().parents[1]
    text = (repo / "docs" / "SHADOW_COMPARISON_RUNBOOK.md").read_text(
        encoding="utf-8")
    assert "not-applicable" in text or "不适用" in text
    assert "redirect" in text.lower() or "改道" in text
